"use client"

import { classNames } from "@/app/(with-context)/voting/classNames"
import { BlurryBackdropBox } from "@/components/BlurryBackdropBox"
import { Card } from "@/components/Card"
import { ContentContainer } from "@/components/ContentContainer"
import { ModalWindow } from "@/components/ModalWindow"
import { StatCards } from "@/components/StatCards"
import { StyledTable } from "@/components/StyledTable"
import { ColumnObject } from "@/components/StyledTable/types"
import { StyledText } from "@/components/StyledText"
import { useToasts } from "@/components/Toasts"
import { Tooltip } from "@/components/Tooltip"
import { claimRewards } from "@/hooks/hooks"
import { amountToUSDString } from "@/lib/amountToUSDString"
import { useDecoratedProposals } from "@/lib/useDecoratedProposals"
import { useChain } from "@cosmos-kit/react"
import { keyBy } from "lodash"
import Image from "next/image"
import Link from "next/link"
import { MouseEvent, useState } from "react"

export default function RewardsPage() {
  const [isShowingClaimRewardsModal, setIsShowingClaimRewardsModal] =
    useState(false)
  const [claimType, setClaimType] = useState<"native" | "convert">("native")
  const decoratedProposals = useDecoratedProposals({ trancheId: 1 }) ?? []
  const proposalsById = keyBy(decoratedProposals, "proposal_id")
  const allProposalIds = Object.keys(proposalsById).map(Number)
  const [selectedProposalIds, setSelectedProposalIds] =
    useState<number[]>(allProposalIds)
  const { setToasts } = useToasts()
  const { address, getSigningCosmWasmClient } = useChain("neutron")

  const rows = decoratedProposals.map((proposal) => {
    const projectLink = `/voting/${proposal.proposal_id}`

    return {
      _proposal: proposal,

      roundNumber: (
        <>
          1
          <Link href={projectLink} className={classNames.projectLink} />
        </>
      ),

      logo: (
        <>
          {proposal.projectLogoUrl ? (
            <div className="relative size-12">
              <Image
                className="object-contain"
                src={proposal.projectLogoUrl}
                alt={proposal.projectName}
                fill={true}
              />
            </div>
          ) : null}
          <Link href={projectLink} className={classNames.projectLink} />
        </>
      ),

      bidTitleAndProjectName: (
        <>
          <div className="flex flex-col">
            <StyledText variant="h4">{proposal.title}</StyledText>
            <StyledText variant="footnote">{proposal.projectName}</StyledText>
          </div>
          <Link href={projectLink} className={classNames.projectLink} />
        </>
      ),

      token: (
        <>
          {proposal.points
            ? proposal.points[1]
            : proposal.pricedAndNamedTributes.map((tribute, index) => (
                <div key={index}>{tribute.symbol || tribute.denom}</div>
              ))}
          <Link href={projectLink} className={classNames.projectLink} />
        </>
      ),

      polRewards: (
        <>
          {amountToUSDString(proposal.estimatedRewardForUser ?? 0)}
          <Link href={projectLink} className={classNames.projectLink} />
        </>
      ),

      tributeRewards: (
        <>
          {amountToUSDString(proposal.totalTributeValue)}
          <Link href={projectLink} className={classNames.projectLink} />
        </>
      ),

      actions: (
        <>
          <StyledText
            as="button"
            variant="button.primary.small"
            onClick={() =>
              handleClickClaimRewards({ proposalIds: [proposal.proposal_id] })
            }
          >
            Claim
          </StyledText>
          <Link href={projectLink} className={classNames.projectLink} />
        </>
      ),
    }
  })

  type Row = (typeof rows)[number]

  const columns: ColumnObject<Row, keyof Row>[] = [
    {
      key: "roundNumber",
      label: "Round",
      textAlign: "center",
      isSortable: true,
      propsForCells: {
        className: "relative",
      },
      customValueGetter: () => 1,
    },
    {
      key: "logo",
      label: "",
      propsForCells: {
        className: "w-min",
      },
    },
    {
      key: "bidTitleAndProjectName",
      label: "Bid Title / Project Name",
      isSortable: true,
      propsForCells: {
        className: "relative",
      },
      customValueGetter: (row) => row._proposal.title,
    },
    {
      key: "token",
      label: "Token",
      textAlign: "center",
      isSortable: true,
      propsForCells: {
        className: "relative whitespace-nowrap",
      },
      customValueGetter: (row) =>
        row._proposal.points ? row._proposal.points[1] : "",
    },
    // {
    //   key: "polRewards",
    //   label: (
    //     <>
    //       PoL Rewards ($)
    //       <Tooltip tipContents="This number is your share of the PoL rewards generated by this PoL deployment." />
    //     </>
    //   ),
    //   textAlign: "right",
    //   isSortable: true,
    //   propsForCells: {
    //     className: "whitespace-nowrap",
    //   },
    //   customValueGetter: (row) => row._proposal.estimatedRewardForUser ?? 0,
    // },
    {
      key: "tributeRewards",
      label: "Tribute Rewards ($)",
      textAlign: "right",
      propsForCells: {
        className: "whitespace-nowrap",
      },
      isSortable: true,
      customValueGetter: (row) => row._proposal.totalTributeValue ?? 0,
    },
    {
      key: "actions",
      label: "Actions",
      textAlign: "right",
      propsForCells: {
        className: "whitespace-nowrap",
      },
    },
  ]

  function handleClickClaimRewards({
    proposalIds,
  }: { proposalIds?: number[] } = {}) {
    setIsShowingClaimRewardsModal(true)
    setSelectedProposalIds(proposalIds ?? allProposalIds)
  }

  function handleClickCloseClaimRewardsModal(
    event?: MouseEvent<HTMLButtonElement>
  ) {
    event?.preventDefault()
    setIsShowingClaimRewardsModal(false)
  }

  async function handleClickClaimNow(event: MouseEvent<HTMLButtonElement>) {
    event.preventDefault()
    setToasts([
      {
        message: "Claiming rewards...",
        variant: "working",
      },
    ])

    await Promise.all(
      selectedProposalIds.map(async (proposalId) => {
        const proposal = proposalsById[proposalId]
        await claimRewards(
          getSigningCosmWasmClient,
          address!,
          proposal.round_id,
          proposal.tranche_id,
          proposalId
        )
      })
    )

    setToasts([])
  }

  return (
    <>
      <StatCards>
        <StatCards.YourAPRCurrentRound />
        <StatCards.YourAPRHistorical />
        <StatCards.YourTotalRewardsValue />
      </StatCards>

      <ContentContainer className="gap-12 py-12">
        <div className="flex items-center justify-between">
          <StyledText variant="h2">Your Rewards</StyledText>

          <div className="flex items-center gap-6">
            <div className="text-palette-beige">You have unclaimed rewards</div>

            <StyledText
              as="button"
              variant="button.primary"
              onClick={handleClickClaimRewards.bind(null, {
                proposalIds: allProposalIds,
              })}
            >
              Claim All Rewards
            </StyledText>
          </div>
        </div>

        <BlurryBackdropBox>
          <StyledTable columns={columns} rows={rows} />
        </BlurryBackdropBox>
      </ContentContainer>

      <ModalWindow
        isOpen={isShowingClaimRewardsModal}
        onClose={handleClickCloseClaimRewardsModal}
      >
        <form>
          <Card>
            <Card.Header
              className="flex flex-col gap-3"
              title="Claim Your Hydro Rewards"
            >
              <StyledText variant="footnote">
                You can claim your rewards in the native token offered as
                tribute or convert them to ATOM before sending them to your
                wallet.
              </StyledText>
            </Card.Header>

            <Card.Body className="flex flex-col gap-6">
              <div className="flex flex-col gap-2">
                <StyledText
                  as="label"
                  variant="label"
                  className="flex items-center gap-2"
                >
                  <StyledText
                    variant="input.radio"
                    as="input"
                    type="radio"
                    name="claimType"
                    value="native"
                  />
                  Claim rewards in native token
                </StyledText>

                <Tooltip tipContents="Coming soon!">
                  <StyledText
                    as="label"
                    variant="label"
                    className="pointer-events-none flex items-center gap-2 opacity-60"
                  >
                    <StyledText
                      variant="input.radio"
                      disabled
                      as="input"
                      type="radio"
                      name="claimType"
                      value="convert"
                    />
                    Convert rewards to ATOM
                  </StyledText>
                </Tooltip>
              </div>

              <div className="flex flex-col gap-2">
                <StyledText as="label" variant="label">
                  Rewards to be Claimed:
                </StyledText>

                <StyledTable
                  initialSortedColumnKey="amount"
                  columns={[
                    {
                      key: "token",
                      label: "Token",
                      isSortable: true,
                      propsForCells: {
                        className: "!py-1",
                      },
                      customValueGetter: (row) =>
                        row._proposal.points
                          ? row._proposal.points[1]
                          : row._proposal.pricedAndNamedTributes
                              .map((tribute, index) => (
                                <div key={index}>
                                  {tribute.symbol || tribute.denom}
                                </div>
                              ))
                              .join(", "),
                    },
                    {
                      key: "amount",
                      label: "Amount",
                      textAlign: "right",
                      isSortable: true,
                      initialSortDirection: "DESC",
                      propsForCells: {
                        className: "!py-1",
                      },
                      customValueGetter: (row) =>
                        row._proposal.estimatedRewardForUser ?? 0,
                    },
                  ]}
                  rows={selectedProposalIds.map((proposalId) => {
                    const proposal = proposalsById[proposalId]
                    return {
                      _proposal: proposal,

                      token: proposal.points
                        ? proposal.points[1]
                        : proposal.pricedAndNamedTributes.map(
                            (tribute, index) => (
                              <div key={index}>
                                {tribute.symbol || tribute.denom}
                              </div>
                            )
                          ),
                      amount: amountToUSDString(
                        proposal?.estimatedRewardForUser ?? 0
                      ),
                    }
                  })}
                />
              </div>
            </Card.Body>

            <Card.Footer>
              <StyledText
                as="button"
                variant="button.primary"
                onClick={handleClickClaimNow}
              >
                Claim Rewards
              </StyledText>

              <StyledText
                as="button"
                variant="button.secondary"
                onClick={handleClickCloseClaimRewardsModal}
              >
                Cancel
              </StyledText>
            </Card.Footer>
          </Card>
        </form>
      </ModalWindow>
    </>
  )
}
