import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from "@next/third-parties/google";
// import { headers } from 'next/headers'

// import { cookieToInitialState } from 'wagmi'

// import { config } from '@/config'
// import Web3ModalProvider from '@/context'
import { Header } from "./ui/Header";
import { WalletHandler } from "./wallet";
import { Toaster } from "@/components/ui/toaster";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const initialState = cookieToInitialState(config, headers().get('cookie'))
  return (
    <html lang="en">
      <body className={`${inter.className} text-white`}>
        <GoogleTagManager gtmId="G-NZ1F6WL2PM" />
        <Script
          type="text/javascript"
          src="https://www.bugherd.com/sidebarv2.js?apikey=mdyh8j9rijiqijf1qow8tw"
          async={true}
        />

        {/* <Web3ModalProvider initialState={initialState}> */}
        <WalletHandler>
          <Header />
          {children}
          <Toaster />
        </WalletHandler>
        {/* </Web3ModalProvider> */}
      </body>
    </html>
  );
}
