// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.180.0
//   protoc               v3.21.3
// source: interchain_security/ccv/provider/v1/tx.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Header, Misbehaviour } from "../../../../ibc/lightclients/tendermint/v1/tendermint";
import { DuplicateVoteEvidence } from "../../../../tendermint/types/evidence";

export const protobufPackage = "interchain_security.ccv.provider.v1";

export interface MsgAssignConsumerKey {
  /** The chain id of the consumer chain to assign a consensus public key to */
  chainId: string;
  /** The validator address on the provider */
  providerAddr: string;
  /**
   * The consensus public key to use on the consumer.
   * in json string format corresponding to proto-any, ex:
   * `{"@type":"/cosmos.crypto.ed25519.PubKey","key":"Ui5Gf1+mtWUdH8u3xlmzdKID+F3PK0sfXZ73GZ6q6is="}`
   */
  consumerKey: string;
}

export interface MsgAssignConsumerKeyResponse {
}

/**
 * MsgSubmitConsumerMisbehaviour defines a message that reports a light client attack,
 * also known as a misbehaviour, observed on a consumer chain
 */
export interface MsgSubmitConsumerMisbehaviour {
  submitter: string;
  /**
   * The Misbehaviour of the consumer chain wrapping
   * two conflicting IBC headers
   */
  misbehaviour: Misbehaviour | undefined;
}

export interface MsgSubmitConsumerMisbehaviourResponse {
}

/**
 * MsgSubmitConsumerDoubleVoting defines a message that reports
 * a double signing infraction observed on a consumer chain
 */
export interface MsgSubmitConsumerDoubleVoting {
  submitter: string;
  /**
   * The equivocation of the consumer chain wrapping
   * an evidence of a validator that signed two conflicting votes
   */
  duplicateVoteEvidence:
    | DuplicateVoteEvidence
    | undefined;
  /** The light client header of the infraction block */
  infractionBlockHeader: Header | undefined;
}

export interface MsgSubmitConsumerDoubleVotingResponse {
}

export interface MsgOptIn {
  /** the chain id of the consumer chain to opt in to */
  chainId: string;
  /** the validator address on the provider */
  providerAddr: string;
  /**
   * (optional) The consensus public key to use on the consumer in json string format corresponding to proto-any,
   * for example `{"@type":"/cosmos.crypto.ed25519.PubKey","key":"Ui5Gf1+mtWUdH8u3xlmzdKID+F3PK0sfXZ73GZ6q6is="}`.
   * This field is optional and can remain empty (i.e., `consumer_key = ""`). A validator can always change the
   * consumer public key at a later stage by issuing a `MsgAssignConsumerKey` message.
   */
  consumerKey: string;
}

export interface MsgOptInResponse {
}

export interface MsgOptOut {
  /** the chain id of the consumer chain to opt out from */
  chainId: string;
  /** the validator address on the provider */
  providerAddr: string;
}

export interface MsgOptOutResponse {
}

/**
 * MsgSetConsumerCommissionRate allows validators to set
 * a per-consumer chain commission rate
 */
export interface MsgSetConsumerCommissionRate {
  /** The validator address on the provider */
  providerAddr: string;
  /** The chain id of the consumer chain to set a commission rate */
  chainId: string;
  /** The rate to charge delegators on the consumer chain, as a fraction */
  rate: string;
}

export interface MsgSetConsumerCommissionRateResponse {
}

function createBaseMsgAssignConsumerKey(): MsgAssignConsumerKey {
  return { chainId: "", providerAddr: "", consumerKey: "" };
}

export const MsgAssignConsumerKey = {
  encode(message: MsgAssignConsumerKey, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.chainId !== "") {
      writer.uint32(10).string(message.chainId);
    }
    if (message.providerAddr !== "") {
      writer.uint32(18).string(message.providerAddr);
    }
    if (message.consumerKey !== "") {
      writer.uint32(26).string(message.consumerKey);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgAssignConsumerKey {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAssignConsumerKey();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.chainId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.providerAddr = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.consumerKey = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgAssignConsumerKey {
    return {
      chainId: isSet(object.chainId) ? globalThis.String(object.chainId) : "",
      providerAddr: isSet(object.providerAddr) ? globalThis.String(object.providerAddr) : "",
      consumerKey: isSet(object.consumerKey) ? globalThis.String(object.consumerKey) : "",
    };
  },

  toJSON(message: MsgAssignConsumerKey): unknown {
    const obj: any = {};
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    if (message.providerAddr !== "") {
      obj.providerAddr = message.providerAddr;
    }
    if (message.consumerKey !== "") {
      obj.consumerKey = message.consumerKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAssignConsumerKey>, I>>(base?: I): MsgAssignConsumerKey {
    return MsgAssignConsumerKey.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAssignConsumerKey>, I>>(object: I): MsgAssignConsumerKey {
    const message = createBaseMsgAssignConsumerKey();
    message.chainId = object.chainId ?? "";
    message.providerAddr = object.providerAddr ?? "";
    message.consumerKey = object.consumerKey ?? "";
    return message;
  },
};

function createBaseMsgAssignConsumerKeyResponse(): MsgAssignConsumerKeyResponse {
  return {};
}

export const MsgAssignConsumerKeyResponse = {
  encode(_: MsgAssignConsumerKeyResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgAssignConsumerKeyResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgAssignConsumerKeyResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgAssignConsumerKeyResponse {
    return {};
  },

  toJSON(_: MsgAssignConsumerKeyResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgAssignConsumerKeyResponse>, I>>(base?: I): MsgAssignConsumerKeyResponse {
    return MsgAssignConsumerKeyResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgAssignConsumerKeyResponse>, I>>(_: I): MsgAssignConsumerKeyResponse {
    const message = createBaseMsgAssignConsumerKeyResponse();
    return message;
  },
};

function createBaseMsgSubmitConsumerMisbehaviour(): MsgSubmitConsumerMisbehaviour {
  return { submitter: "", misbehaviour: undefined };
}

export const MsgSubmitConsumerMisbehaviour = {
  encode(message: MsgSubmitConsumerMisbehaviour, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.submitter !== "") {
      writer.uint32(10).string(message.submitter);
    }
    if (message.misbehaviour !== undefined) {
      Misbehaviour.encode(message.misbehaviour, writer.uint32(18).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgSubmitConsumerMisbehaviour {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitConsumerMisbehaviour();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.submitter = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.misbehaviour = Misbehaviour.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitConsumerMisbehaviour {
    return {
      submitter: isSet(object.submitter) ? globalThis.String(object.submitter) : "",
      misbehaviour: isSet(object.misbehaviour) ? Misbehaviour.fromJSON(object.misbehaviour) : undefined,
    };
  },

  toJSON(message: MsgSubmitConsumerMisbehaviour): unknown {
    const obj: any = {};
    if (message.submitter !== "") {
      obj.submitter = message.submitter;
    }
    if (message.misbehaviour !== undefined) {
      obj.misbehaviour = Misbehaviour.toJSON(message.misbehaviour);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitConsumerMisbehaviour>, I>>(base?: I): MsgSubmitConsumerMisbehaviour {
    return MsgSubmitConsumerMisbehaviour.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitConsumerMisbehaviour>, I>>(
    object: I,
  ): MsgSubmitConsumerMisbehaviour {
    const message = createBaseMsgSubmitConsumerMisbehaviour();
    message.submitter = object.submitter ?? "";
    message.misbehaviour = (object.misbehaviour !== undefined && object.misbehaviour !== null)
      ? Misbehaviour.fromPartial(object.misbehaviour)
      : undefined;
    return message;
  },
};

function createBaseMsgSubmitConsumerMisbehaviourResponse(): MsgSubmitConsumerMisbehaviourResponse {
  return {};
}

export const MsgSubmitConsumerMisbehaviourResponse = {
  encode(_: MsgSubmitConsumerMisbehaviourResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgSubmitConsumerMisbehaviourResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitConsumerMisbehaviourResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSubmitConsumerMisbehaviourResponse {
    return {};
  },

  toJSON(_: MsgSubmitConsumerMisbehaviourResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitConsumerMisbehaviourResponse>, I>>(
    base?: I,
  ): MsgSubmitConsumerMisbehaviourResponse {
    return MsgSubmitConsumerMisbehaviourResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitConsumerMisbehaviourResponse>, I>>(
    _: I,
  ): MsgSubmitConsumerMisbehaviourResponse {
    const message = createBaseMsgSubmitConsumerMisbehaviourResponse();
    return message;
  },
};

function createBaseMsgSubmitConsumerDoubleVoting(): MsgSubmitConsumerDoubleVoting {
  return { submitter: "", duplicateVoteEvidence: undefined, infractionBlockHeader: undefined };
}

export const MsgSubmitConsumerDoubleVoting = {
  encode(message: MsgSubmitConsumerDoubleVoting, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.submitter !== "") {
      writer.uint32(10).string(message.submitter);
    }
    if (message.duplicateVoteEvidence !== undefined) {
      DuplicateVoteEvidence.encode(message.duplicateVoteEvidence, writer.uint32(18).fork()).ldelim();
    }
    if (message.infractionBlockHeader !== undefined) {
      Header.encode(message.infractionBlockHeader, writer.uint32(26).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgSubmitConsumerDoubleVoting {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitConsumerDoubleVoting();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.submitter = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.duplicateVoteEvidence = DuplicateVoteEvidence.decode(reader, reader.uint32());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.infractionBlockHeader = Header.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSubmitConsumerDoubleVoting {
    return {
      submitter: isSet(object.submitter) ? globalThis.String(object.submitter) : "",
      duplicateVoteEvidence: isSet(object.duplicateVoteEvidence)
        ? DuplicateVoteEvidence.fromJSON(object.duplicateVoteEvidence)
        : undefined,
      infractionBlockHeader: isSet(object.infractionBlockHeader)
        ? Header.fromJSON(object.infractionBlockHeader)
        : undefined,
    };
  },

  toJSON(message: MsgSubmitConsumerDoubleVoting): unknown {
    const obj: any = {};
    if (message.submitter !== "") {
      obj.submitter = message.submitter;
    }
    if (message.duplicateVoteEvidence !== undefined) {
      obj.duplicateVoteEvidence = DuplicateVoteEvidence.toJSON(message.duplicateVoteEvidence);
    }
    if (message.infractionBlockHeader !== undefined) {
      obj.infractionBlockHeader = Header.toJSON(message.infractionBlockHeader);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitConsumerDoubleVoting>, I>>(base?: I): MsgSubmitConsumerDoubleVoting {
    return MsgSubmitConsumerDoubleVoting.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitConsumerDoubleVoting>, I>>(
    object: I,
  ): MsgSubmitConsumerDoubleVoting {
    const message = createBaseMsgSubmitConsumerDoubleVoting();
    message.submitter = object.submitter ?? "";
    message.duplicateVoteEvidence =
      (object.duplicateVoteEvidence !== undefined && object.duplicateVoteEvidence !== null)
        ? DuplicateVoteEvidence.fromPartial(object.duplicateVoteEvidence)
        : undefined;
    message.infractionBlockHeader =
      (object.infractionBlockHeader !== undefined && object.infractionBlockHeader !== null)
        ? Header.fromPartial(object.infractionBlockHeader)
        : undefined;
    return message;
  },
};

function createBaseMsgSubmitConsumerDoubleVotingResponse(): MsgSubmitConsumerDoubleVotingResponse {
  return {};
}

export const MsgSubmitConsumerDoubleVotingResponse = {
  encode(_: MsgSubmitConsumerDoubleVotingResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgSubmitConsumerDoubleVotingResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSubmitConsumerDoubleVotingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSubmitConsumerDoubleVotingResponse {
    return {};
  },

  toJSON(_: MsgSubmitConsumerDoubleVotingResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSubmitConsumerDoubleVotingResponse>, I>>(
    base?: I,
  ): MsgSubmitConsumerDoubleVotingResponse {
    return MsgSubmitConsumerDoubleVotingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSubmitConsumerDoubleVotingResponse>, I>>(
    _: I,
  ): MsgSubmitConsumerDoubleVotingResponse {
    const message = createBaseMsgSubmitConsumerDoubleVotingResponse();
    return message;
  },
};

function createBaseMsgOptIn(): MsgOptIn {
  return { chainId: "", providerAddr: "", consumerKey: "" };
}

export const MsgOptIn = {
  encode(message: MsgOptIn, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.chainId !== "") {
      writer.uint32(10).string(message.chainId);
    }
    if (message.providerAddr !== "") {
      writer.uint32(18).string(message.providerAddr);
    }
    if (message.consumerKey !== "") {
      writer.uint32(26).string(message.consumerKey);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgOptIn {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgOptIn();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.chainId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.providerAddr = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.consumerKey = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgOptIn {
    return {
      chainId: isSet(object.chainId) ? globalThis.String(object.chainId) : "",
      providerAddr: isSet(object.providerAddr) ? globalThis.String(object.providerAddr) : "",
      consumerKey: isSet(object.consumerKey) ? globalThis.String(object.consumerKey) : "",
    };
  },

  toJSON(message: MsgOptIn): unknown {
    const obj: any = {};
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    if (message.providerAddr !== "") {
      obj.providerAddr = message.providerAddr;
    }
    if (message.consumerKey !== "") {
      obj.consumerKey = message.consumerKey;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgOptIn>, I>>(base?: I): MsgOptIn {
    return MsgOptIn.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgOptIn>, I>>(object: I): MsgOptIn {
    const message = createBaseMsgOptIn();
    message.chainId = object.chainId ?? "";
    message.providerAddr = object.providerAddr ?? "";
    message.consumerKey = object.consumerKey ?? "";
    return message;
  },
};

function createBaseMsgOptInResponse(): MsgOptInResponse {
  return {};
}

export const MsgOptInResponse = {
  encode(_: MsgOptInResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgOptInResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgOptInResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgOptInResponse {
    return {};
  },

  toJSON(_: MsgOptInResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgOptInResponse>, I>>(base?: I): MsgOptInResponse {
    return MsgOptInResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgOptInResponse>, I>>(_: I): MsgOptInResponse {
    const message = createBaseMsgOptInResponse();
    return message;
  },
};

function createBaseMsgOptOut(): MsgOptOut {
  return { chainId: "", providerAddr: "" };
}

export const MsgOptOut = {
  encode(message: MsgOptOut, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.chainId !== "") {
      writer.uint32(10).string(message.chainId);
    }
    if (message.providerAddr !== "") {
      writer.uint32(18).string(message.providerAddr);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgOptOut {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgOptOut();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.chainId = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.providerAddr = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgOptOut {
    return {
      chainId: isSet(object.chainId) ? globalThis.String(object.chainId) : "",
      providerAddr: isSet(object.providerAddr) ? globalThis.String(object.providerAddr) : "",
    };
  },

  toJSON(message: MsgOptOut): unknown {
    const obj: any = {};
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    if (message.providerAddr !== "") {
      obj.providerAddr = message.providerAddr;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgOptOut>, I>>(base?: I): MsgOptOut {
    return MsgOptOut.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgOptOut>, I>>(object: I): MsgOptOut {
    const message = createBaseMsgOptOut();
    message.chainId = object.chainId ?? "";
    message.providerAddr = object.providerAddr ?? "";
    return message;
  },
};

function createBaseMsgOptOutResponse(): MsgOptOutResponse {
  return {};
}

export const MsgOptOutResponse = {
  encode(_: MsgOptOutResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgOptOutResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgOptOutResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgOptOutResponse {
    return {};
  },

  toJSON(_: MsgOptOutResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgOptOutResponse>, I>>(base?: I): MsgOptOutResponse {
    return MsgOptOutResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgOptOutResponse>, I>>(_: I): MsgOptOutResponse {
    const message = createBaseMsgOptOutResponse();
    return message;
  },
};

function createBaseMsgSetConsumerCommissionRate(): MsgSetConsumerCommissionRate {
  return { providerAddr: "", chainId: "", rate: "" };
}

export const MsgSetConsumerCommissionRate = {
  encode(message: MsgSetConsumerCommissionRate, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.providerAddr !== "") {
      writer.uint32(10).string(message.providerAddr);
    }
    if (message.chainId !== "") {
      writer.uint32(18).string(message.chainId);
    }
    if (message.rate !== "") {
      writer.uint32(26).string(message.rate);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgSetConsumerCommissionRate {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetConsumerCommissionRate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.providerAddr = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.chainId = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.rate = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MsgSetConsumerCommissionRate {
    return {
      providerAddr: isSet(object.providerAddr) ? globalThis.String(object.providerAddr) : "",
      chainId: isSet(object.chainId) ? globalThis.String(object.chainId) : "",
      rate: isSet(object.rate) ? globalThis.String(object.rate) : "",
    };
  },

  toJSON(message: MsgSetConsumerCommissionRate): unknown {
    const obj: any = {};
    if (message.providerAddr !== "") {
      obj.providerAddr = message.providerAddr;
    }
    if (message.chainId !== "") {
      obj.chainId = message.chainId;
    }
    if (message.rate !== "") {
      obj.rate = message.rate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetConsumerCommissionRate>, I>>(base?: I): MsgSetConsumerCommissionRate {
    return MsgSetConsumerCommissionRate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetConsumerCommissionRate>, I>>(object: I): MsgSetConsumerCommissionRate {
    const message = createBaseMsgSetConsumerCommissionRate();
    message.providerAddr = object.providerAddr ?? "";
    message.chainId = object.chainId ?? "";
    message.rate = object.rate ?? "";
    return message;
  },
};

function createBaseMsgSetConsumerCommissionRateResponse(): MsgSetConsumerCommissionRateResponse {
  return {};
}

export const MsgSetConsumerCommissionRateResponse = {
  encode(_: MsgSetConsumerCommissionRateResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MsgSetConsumerCommissionRateResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMsgSetConsumerCommissionRateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MsgSetConsumerCommissionRateResponse {
    return {};
  },

  toJSON(_: MsgSetConsumerCommissionRateResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MsgSetConsumerCommissionRateResponse>, I>>(
    base?: I,
  ): MsgSetConsumerCommissionRateResponse {
    return MsgSetConsumerCommissionRateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MsgSetConsumerCommissionRateResponse>, I>>(
    _: I,
  ): MsgSetConsumerCommissionRateResponse {
    const message = createBaseMsgSetConsumerCommissionRateResponse();
    return message;
  },
};

/** Msg defines the Msg service. */
export interface Msg {
  AssignConsumerKey(request: MsgAssignConsumerKey): Promise<MsgAssignConsumerKeyResponse>;
  SubmitConsumerMisbehaviour(request: MsgSubmitConsumerMisbehaviour): Promise<MsgSubmitConsumerMisbehaviourResponse>;
  SubmitConsumerDoubleVoting(request: MsgSubmitConsumerDoubleVoting): Promise<MsgSubmitConsumerDoubleVotingResponse>;
  OptIn(request: MsgOptIn): Promise<MsgOptInResponse>;
  OptOut(request: MsgOptOut): Promise<MsgOptOutResponse>;
  SetConsumerCommissionRate(request: MsgSetConsumerCommissionRate): Promise<MsgSetConsumerCommissionRateResponse>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
